run:
  timeout: 5m
  tests: true
  exclude-dirs:
    - vendor
    - testdata

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional linters
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocyclo
    - dupl
    - gocritic
    - revive
    - bodyclose
    - noctx
    - unparam
    - wastedassign
    - whitespace
  
  disable:
    - typecheck

linters-settings:
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  dupl:
    threshold: 100
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - paramTypeCombine

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst


